### ISSUE TITLE
Text Splitting doesn't properly on 48.2

### ISSUE THREAD

**Issue by ziyafenn** [joshwayne/jw-sketch-plugins#13]
Hi there! The issue is, text splitting doesn't work when there is no line break between text lines.
It works only i manually enter line breaks and still, it works bit buggy: you have to select/edit each layer to make them not overflow each other. 

Thanks

**Comment by joshwayne** [comment]
Hey @ziyafenn, thanks for letting me know. Can you tell me more about what you expect to happen when you use the plugin? Are you looking for the plugin to break up text to new layers wherever it wraps?

As for the overlapping, I'm aware of the issue. It popped up with one of the recent Sketch updates. I'm trying to find some time to debug it and put out an update.

**Comment by ziyafenn** [comment]
I expect it to split the text into separate layers in these cases:

**List with single or double line breaks** i.e.

```
Item One
Item Two
Item Three
```
 or

```
Item One

Item Two

Item Three
```

_My current issue was that it worked only with a double line break and with overlapping._

**Text (line or paragraph) with spaces** i.e.

`one two three four`

Thanks!

**Comment by joshwayne** [comment]
Hm, I've tested it for the first two cases and it seems to work for me with both single and double line breaks. I've intentionally removed any lines that don't have characters in them, so it won't work as expected if you're expecting blank lines to create new blank layers.

As for the third case (`Text (line or paragraph) with spaces`), that's simply a use case that I never have. From my personal experience, it feels like an edge case. I won't be supporting it in my branch, but you're welcome to fork the repo and create a version of the plugin that fits your needs.

I'm leaving the issue open because I need to spend some time figuring out the line height bug and how to fix it so layers stay where they're suppose to be.

**Comment by ziyafenn** [comment]
That's weird, i made a text list and copied it into sketch then used the plugin and it worked. 
Dunno what was the problem last time.

Thanks!
